[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:evolution-api]
command=/start-evolution.sh
directory=/evolution-src
autostart=true
autorestart=true
startsecs=10
startretries=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=
    SERVER_PORT="8080",
    SERVER_TYPE="http",
    CORS_ORIGIN="*",
    DEL_INSTANCE="false",
    DATABASE_ENABLED="%(ENV_DATABASE_ENABLED)s",
    DATABASE_PROVIDER="%(ENV_DATABASE_PROVIDER)s",
    DATABASE_CONNECTION_URI="%(ENV_DATABASE_CONNECTION_URI)s",
    DATABASE_SAVE_DATA_INSTANCE="true",
    DATABASE_SAVE_DATA_NEW_MESSAGE="true",
    DATABASE_SAVE_MESSAGE_UPDATE="true",
    DATABASE_SAVE_DATA_CONTACTS="true",
    DATABASE_SAVE_DATA_CHATS="true",
    CACHE_REDIS_ENABLED="%(ENV_CACHE_REDIS_ENABLED)s",
    CACHE_REDIS_URI="%(ENV_CACHE_REDIS_URI)s",
    CACHE_REDIS_PREFIX_KEY="evolution",
    AUTHENTICATION_API_KEY="%(ENV_EVOLUTION_API_KEY)s",
    AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES="true",
    QRCODE_LIMIT="30",
    WEBHOOK_GLOBAL_ENABLED="false"

[program:fastapi-proxy]
command=/venv/bin/python /app/main.py
directory=/app
autostart=true
autorestart=true
startsecs=8
startretries=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
